name: task
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  dio: ^5.2.1+1
  intl: ^0.17.0
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  flutter_gif: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria-Black.ttf
        - asset: assets/fonts/Alexandria-Bold.ttf
        - asset: assets/fonts/Alexandria-ExtraBold.ttf
        - asset: assets/fonts/Alexandria-ExtraLight.ttf
        - asset: assets/fonts/Alexandria-Light.ttf
        - asset: assets/fonts/Alexandria-Medium.ttf
        - asset: assets/fonts/Alexandria-Regular.ttf
        - asset: assets/fonts/Alexandria-SemiBold.ttf
        - asset: assets/fonts/Alexandria-Thin.ttf
